const Routes = {
  homeAnchor: '/#Home',
  home: '/',
  iwiMembersAnchor: '/#IwiMembers',
  aboutAnchor: '/#About',
  communityLinksAnchor: '/#CommunityLinks',
  newsFeedAnchor: '/#NewsFeeds',
  newsFeeds: '/NewsFeeds',
  newsFeed: '/NewsFeeds/:nfid',
  interactiveMapAnchor: '/#InteractiveMap',
  volunteersAnchor: '/#Volunteers',
  // volunteerRegistration: '/Volunteer',
  privacyPolicy: '/PrivacyPolicy',
  termsOfUse: '/TermsOfUse',
  aboutUs: '/AboutUs',
  contactUs: '/ContactUs',
  facebookLinks: '/FBFeeds',
  // facebookLink: '/FacebookLinks/:fid',
  eventsAnchor: '/#Wananga',
  events: '/Wananga',
  event: '/Wananga/:evid',
  iwiChair: '/AboutUs/:imid',
  projectsAnchor: '/#Projects',
  projectsPage: '/Projects',
  projectPage: '/Projects/:pid',
  resourcesAnchor: '/#Resources',
  resourcesPage: '/Resources',
  // resourceCardPage: '/ResourceCard',
  economicDevelopmentsAnchor: '/#EconomicDevelopments',
  economicDevelopmentsPage: '/EconomicDevelopments',
  // economicDevelopmentCardPage: '/EconomicDevelopmentCard',
  mediaListAnchor: '/#Media',
  mediaListPage: '/Media',
  mediaPage: '/Media/:nfid',
  covidListAnchor: '/#Covid',
  covidListPage: '/Covid',
  covidPage: '/Covid/:cvid'
};

export default Routes;
