const Routes = {
  homeAnchor: '/#Home',
  home: '/',
  iwiMembersAnchor: '/#IwiMembers',
  aboutAnchor: '/#About',
  communityLinksAnchor: '/#CommunityLinks',
  newsFeedAnchor: '/#NewsFeed',
  newsFeeds: '/NewsFeeds',
  newsFeed: '/NewsFeeds/:nfid',
  interactiveMapAnchor: '/#InteractiveMap',
  volunteersAnchor: '/#Volunteers',
  volunteerRegistration: '/Volunteer',
  privacyPolicy: '/PrivacyPolicy',
  termsOfUse: '/TermsOfUse',
  aboutUs: '/AboutUs',
  contactUs: '/ContactUs',
  facebookLinks: '/RSS',
  facebookLink: '/FacebookLinks/:fid',
  eventsAnchor: '/#Wananga',
  events: '/Wananga',
  event: '/Wananga/:evid',
  iwiChair: '/AboutUs/:imid',
  projectsAnchor: '/#Projects',
  projectsPage: '/Projects',
  projectPage: '/Project/:pid',
  resourcesAnchor: '/#Resources',
  resourcesPage: '/Resources'
};

export default Routes;
